spring:
  data:
    mongodb:
        database: digital_classroom
        port: 27017
        host: localhost
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1026154975007-frvgtfmlgccmbmmeg88h0lsv8t8flsfk.apps.googleusercontent.com
            clientSecret: Dt2z0Y6Qa-kiFZRigSRZlDGS
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
              - https://www.googleapis.com/auth/drive
          facebook: 
              clientId: 121189305185277
              clientSecret: 42ffe5aa7379e8326387e0fe16f34132
              redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - public_profile
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
